name: Prueba GitHubActions
run-name: Prueba API
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        -uses: actions/checkout@v5
        -name: Configurar JDK 21
        uses: actions/setup-java@v5
        with:
            distribution: 'temurin'
            java-version: '21'
        -name: Build with Maven
        run: mvn clean verify